### ISSUE TITLE
服务器地址如何修改

### ISSUE THREAD

**Issue by xuzhuo99hy** [gybin02/RouterKit#5]
#服务器地址
deployUrl=http\://192.168.10.230\:8081/nexus/content/repositories/snapshots/
deployReleaseUrl=http\://192.168.10.230\:8081/nexus/content/repositories/releases/
thirdpartyUrl=http\://192.168.10.230\:8081/nexus/content/repositories/thirdparty/

**Comment by gybin02** [comment]
这个不用管，这个是我内部打Maven包的地址
